#NUMPY

In [ ]:
import numpy as np
arr=[10,60,89,90,75]
print(np.array(arr))

[10 60 89 90 75]


#ADDING THE ARRAY


In [ ]:
arr1=[1,2,3,4,5]
arr2=[6,7,8,9,10]
print(np.array(arr1)+np.array(arr2))

[ 7  9 11 13 15]


#ERROR IN INVALID ASSIGNMENT OF VALUES

In [ ]:
arr1=[1,2,3,4]
arr2=[6,7,8,9,10]
print(np.array(arr1)+np.array(arr2))

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

#RESHAPE THE ARRAY

In [ ]:
arr3=[9,7,10,11,13,15,90,56,87]
print(np.array(arr3).reshape(3,3))

[[ 9  7 10]
 [11 13 15]
 [90 56 87]]


In [ ]:
arr3=[9,7,10,11,13,15,90,56]
print(np.array(arr3).reshape(3,3))

ValueError: cannot reshape array of size 8 into shape (3,3)

TRANSPOSE THE ARRAY

In [ ]:
arr4=[2,9,6,4,5,7]
a=np.array(arr4).reshape(2,3)
print(a)
print(a.transpose())

[[2 9 6]
 [4 5 7]]
[[2 4]
 [9 5]
 [6 7]]


#ndim to know dimension

In [ ]:
f=9
l=np.array([10,20,30,40])
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
d=np.array([[[1,2],[3,6],[6,7],[7,10]]])
#print(f.ndim)
print(l.ndim)
print(c.ndim)
print(d.ndim)

1
2
3


#copying the array

In [ ]:
m=[1,2,3,4,5]
b=m.copy()
print(b)


[1, 2, 3, 4, 5]


#ONCE FUNCTION

In [ ]:
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


#ZEROS FUNCTION


In [ ]:
a=np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


#EYE FUNCTION

In [ ]:
c=np.eye(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#FULL FUNCTION

In [ ]:
d=np.full((2,2),5)
print(d)

[[5 5]
 [5 5]]


#ARANGE FUNCTION

In [ ]:
e=np.arange(0,10,2)
print(e)

[0 2 4 6 8]


#linspace function

In [ ]:
f=np.linspace(0,10,5)
print(f)

[ 0.   2.5  5.   7.5 10. ]


#SLICING THE ARRAY

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0][0])
print(a[0][1])
print(a[0][2])

1
2
3


In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0][0])
print(a[1][2])
print(a[1,2])
print(a[2:,1:])

1
6
6
[[8 9]]


#FLATTEN

In [ ]:
arr=np.array([[1,2,3],[4,3,4]])
print(arr.flatten())

[1 2 3 4 3 4]


#sum(),mean(),min(),max(),axis 0 sum, axis 1 sum

In [ ]:
arr1=np.array([[3,2,4],[6,4,2]])
print("Sum:",np.sum(arr1))
print("Mean:",np.mean(arr1))
print("Min:",np.min(arr1))
print("Max:",np.max(arr1))
print("Axis 0 Sum:",np.sum(arr1,axis=0))
print("Axis 1 Sum:",np.sum(arr1,axis=1))

Sum: 21
Mean: 3.5
Min: 2
Max: 6
Axis 0 Sum: [9 6 6]
Axis 1 Sum: [ 9 12]


#Randint function

In [ ]:
print(np.random.randint(1,20,100))

[ 1 14  7  4 17 12 15  7 10  4 19  7  3  9  6  7  4  4  1 19 11  4  8  1
  7  7  1 10 12 10 11 16  8 12  5  6 16 15  6  3  5 16 14 15  3  9  7  5
 10  3  6 19 16 11 17  4  3 15 18  5  1 14  9 14  3  1  6  2  5  3 10 18
 12 12 15 17  9 12  4 18  4 17 18 17 13  3  7 18 17 17 17  8  7 14  9 12
  8  7 18 18]


#RADIAN TO DEGREE & DEGREE TO RADIAN

In [ ]:
l=[10,67,34,65]
print(np.radians(l))
print(np.degrees(l))

[0.17453293 1.1693706  0.59341195 1.13446401]
[ 572.95779513 3838.81722738 1948.05650344 3724.22566835]
